V2
Elikill58/Negativity pull request #241
Opened 2021-03-22 20:39 UTC by SalersFR

Added Clicker, Scaffold and Reach checks

2021-04-04 12:33 UTC, Elikill58 requested changes
Globaly, there isn't any check if check is active. They are configurable in module config file (at the end).
The default required reliability is 60, and so when it's 56, we could not get alert for it.
Else, I try all of those, but I didn't get alert.

I suggest you to try the code, and not just code blindly.

2021-04-04 12:33 UTC, Elikill58 commented on common/src/com/elikill58/negativity/common/protocols/ForceField.java
> +								"net.minecraft.server." + Adapter.getAdapter().getServerVersion() + ".EntityUseAction"))
Same issue as autoClick

2021-04-04 12:33 UTC, Elikill58 commented on common/src/com/elikill58/negativity/common/protocols/ForceField.java
> +		Entity victim = data.getLastHitted();
As all the time, don't check if check is active

2021-04-04 12:33 UTC, Elikill58 commented on common/src/com/elikill58/negativity/common/protocols/Scaffold.java
> +				Negativity.alertMod(ReportType.VIOLATION,data.getPlayer(), this, 56, "NoSwing", "Last packet was not an ArmAnimation packet");
Check name have to be like "no-swing" to correspond to others.
56% of reliability is below the default needed reliability (60), so never showed.
No check if check is active

2021-04-04 12:33 UTC, Elikill58 commented on common/src/com/elikill58/negativity/common/protocols/Sneak.java
> +		Cheat sneak = Cheat.forKey(SNEAK);
Useless because the cheat is itself

2021-04-04 12:33 UTC, Elikill58 commented on common/src/com/elikill58/negativity/common/protocols/Speed.java
>  public class Speed extends Cheat implements Listeners {
The alone thing which is changed is global refactor, but no new content ?

2021-04-04 12:33 UTC, Elikill58 commented on common/src/com/elikill58/negativity/common/protocols/Critical.java
> +		NegativityPlayer data = NegativityPlayer.getNegativityPlayer(event.getPlayer());
Useless code, just keep resources

2021-07-21 17:58 UTC, Waveium commented on common/src/com/elikill58/negativity/common/protocols/Fly.java
> +		if (diff < 0.30 && diff > 0.2 && player.getLocation().add(+2, -2, +2).getBlock().getType() == Materials.AIR
> The check don't work, I never get alert for it
It worked for me, (moon 3.1)

2021-07-21 18:44 UTC, Elikill58 commented on common/src/com/elikill58/negativity/common/protocols/Fly.java
> +		if (diff < 0.30 && diff > 0.2 && player.getLocation().add(+2, -2, +2).getBlock().getType() == Materials.AIR
Ok thanks for info, I will try it again

2021-07-22 09:55 UTC, SalersFR commented on common/src/com/elikill58/negativity/common/protocols/Fly.java
> +		if (diff < 0.30 && diff > 0.2 && player.getLocation().add(+2, -2, +2).getBlock().getType() == Materials.AIR
Also add !isReallyOnGround(player) to the if statement

2021-07-22 22:00 UTC, Elikill58 commented on common/src/com/elikill58/negativity/common/protocols/Fly.java
> +		if (diff < 0.30 && diff > 0.2 && player.getLocation().add(+2, -2, +2).getBlock().getType() == Materials.AIR
Added. I close this discussion !

2021-08-17 22:24 UTC, closed without merging