Edit check structure
Elikill58/Negativity pull request #268
Opened 2021-06-17 18:52 UTC by Elikill58

Edit the structure of check to correspond to command one, and to easier edit conditions

2021-06-19 11:25 UTC, RedNesto requested changes
L'introduction de PlayerEvent devrait être fait dans un commit différent complètement séparé de cette PR.

2021-06-19 11:25 UTC, RedNesto commented on common/src/com/elikill58/negativity/common/protocols/ProtocolManager.java
> +	}
```suggestion
	private final List<CheckMethod> allChecks = new ArrayList<>();
	
	public ProtocolManager(List<Cheat> cheats) {
		for (Cheat cheat : cheats) {
			for (Method possibleMethod : cheat.getClass().getMethods()) {
				Check check = possibleMethod.getAnnotation(Check.class);
				if (check == null) {
					continue;
				}
				
				Class<?>[] parameterTypes = possibleMethod.getParameterTypes();
				if (parameterTypes.length != 1) {
					Adapter.getAdapter().getLogger().warn("Method for check " + check.name() + " must have exactly one parameter.");
					continue;
				}
				
				if (!PlayerEvent.class.isAssignableFrom(parameterTypes[0])) {
					Adapter.getAdapter().getLogger().warn("Parameter of check method " + possibleMethod.getName() + " must be a subclass of PlayerEvent.");
					continue;
				}
				
				allChecks.add(new CheckMethod(cheat, check, possibleMethod));
			}
		}
	}
```

Il faut vraiment valider le paramètre de la méthode, et logger un warning si la méthode d'un check n'est pas valide.

Le commentaire est faux d'ailleurs, `Cheats.CHEATS` ne contient pas de données "statiques" (on reload les cheats aussi je te rappelle.)

C'est une préférence personnelle (qui a probablement changée depuis quelques années) mais j'éviterais d'utiliser forEach avec des lambdas alors qu'un foreach classique fait complètement l'affaire. C'est toujours pratique avec des références de méthode par contre.

2021-06-19 11:25 UTC, RedNesto commented on common/src/com/elikill58/negativity/common/protocols/ProtocolManager.java
> +					if(condition.check(p)) {
C'est pas logique, remplir toutes les conditions devrait faire exécuter le check, alors que là remplir au moins une condition skip le check.

D'ailleurs le commentaire un peu plus haut est inutile selon moi, le code est suffisamment expressif (bon sauf les conditions inversées.)

2021-06-19 11:25 UTC, RedNesto commented on common/src/com/elikill58/negativity/common/protocols/ProtocolManager.java
> +				if(!NegativityPlayer.getNegativityPlayer(p).hasDetectionActive(check.getCheat()))
Vu que tu accèdes déjà au NegativityPlayer ici, pourquoi ne pas le passer en paramètre optionnel pour les checks ?

2021-06-19 11:25 UTC, RedNesto commented on common/src/com/elikill58/negativity/common/protocols/ProtocolManager.java
> +public class ProtocolManager implements Listeners {
Pourquoi ne pas l'appeler `CheckManager` ? c'est pas révolutionnaire mais au moins on évite d'utiliser protocol que je ne trouve pas logique dans l'état actuel du plugin (les détections ne sont pas toutes basées sur des protocoles, à moins que tu ne fasses référence à quelque chose d'autre.)

2021-06-19 11:43 UTC, RedNesto commented on common/src/com/elikill58/negativity/api/protocols/CheckConditions.java
> +	private CheckConditions(Function<Player, Boolean> function) {
Ah oui j'avais oublié: utilise Predicate<Player>

2021-06-19 16:14 UTC, Elikill58 commented on common/src/com/elikill58/negativity/api/events/negativity/PlayerCheatAlertEvent.java
>  	private final Player p;
Effectivement, je dois l'enlever comme j'ai fais pour plusieurs events.
C'est vrai que dans un commit séparé (voir directement dans v2) aurait été mieux

2021-06-19 16:14 UTC, Elikill58 commented on common/src/com/elikill58/negativity/api/protocols/CheckConditions.java
> +	private CheckConditions(Function<Player, Boolean> function) {
Bonne idée !

2021-06-19 16:14 UTC, Elikill58 commented on common/src/com/elikill58/negativity/common/protocols/ProtocolManager.java
> +public class ProtocolManager implements Listeners {
C'est vrai que ça serai un meilleur nom

2021-06-19 16:14 UTC, Elikill58 commented on common/src/com/elikill58/negativity/common/protocols/ProtocolManager.java
> +				if(!NegativityPlayer.getNegativityPlayer(p).hasDetectionActive(check.getCheat()))
Effectivement, pourquoi pas

2021-06-19 16:14 UTC, Elikill58 commented on common/src/com/elikill58/negativity/common/protocols/ProtocolManager.java
> +					if(condition.check(p)) {
Ce sont des conditions filtrante l'arrivé dans le check, qui globalement remplace des : `if(check) return;`

2021-06-19 16:39 UTC, RedNesto commented on common/src/com/elikill58/negativity/common/protocols/ProtocolManager.java
> +					if(condition.check(p)) {
Oui ça je sais, je pense juste que tu devrais inverser la condition.

Si un check utilise SURVIVAL alors on a `if (SURVIVAL) return;`, donc le check ne s'exécute PAS si le joueur est en survie.

2021-06-19 16:39 UTC, RedNesto commented on common/src/com/elikill58/negativity/common/protocols/ProtocolManager.java
> +					if(condition.check(p)) {
Oui ça je sais, je pense juste que tu devrais inverser la condition.

Si un check utilise SURVIVAL alors on a `if (SURVIVAL) return;`, donc le check ne s'exécute PAS si le joueur est en survie.

2021-06-19 19:54 UTC, RedNesto commented on common/src/com/elikill58/negativity/common/protocols/CheckManager.java
> +				allChecks.add(new CheckMethod(cheat, check, possibleMethod, hasNegativityPlayer));
Du coup il se passe rien si la méthode a plus de 2 paramètres ?

2021-06-19 20:31 UTC, RedNesto commented on common/src/com/elikill58/negativity/common/protocols/XRay.java
> +		NegativityAccount.get(p.getUniqueId()).getMinerate().addMine(MinerateType.fromId(e.getBlock().getType().getId()), p);
Tu peux mettre le NegativityPlayer en paramètre

2021-06-19 20:44 UTC, Elikill58 commented on common/src/com/elikill58/negativity/common/protocols/XRay.java
> +		NegativityAccount.get(p.getUniqueId()).getMinerate().addMine(MinerateType.fromId(e.getBlock().getType().getId()), p);
C'est NegativityAccount ici

2021-06-19 20:49 UTC, RedNesto commented on common/src/com/elikill58/negativity/common/protocols/XRay.java
> +		NegativityAccount.get(p.getUniqueId()).getMinerate().addMine(MinerateType.fromId(e.getBlock().getType().getId()), p);
HAH!

Du coup je pense avoir tout dis. Fais-toi plaisir maintenant.

2021-06-20 18:26 UTC, RedNesto approved these changes

2021-06-20 18:27 UTC, merged