V2 updated readme
Elikill58/Negativity pull request #333
Opened 2022-08-19 08:21 UTC by Farmeurimmo

I have updated the readme. 

I have tested everything that I modified. (like needed spigot version jars)

2022-08-19 09:57 UTC, RedNesto requested changes

2022-08-19 12:17 UTC, Farmeurimmo commented on README.md
> +4. You should use buildtools for Spigot 1.17/1.18/1.18.2/1.19 (or comment them in `settings.gradle`). You need to place the remapped jar in `spigot/spigot18`
Est ce que c'est vraiment nécéssaire de leur faire compiler un jar avec les sources et les docs ?
C'est déjà long sans mais alors avec ils vont y passer la semaine.
Autant directement mettre `java -jar BuildTools.jar --rev <version> --remapped` comme commande à executer?

2022-08-19 12:53 UTC, RedNesto commented on README.md
> +4. You should use buildtools for Spigot 1.17/1.18/1.18.2/1.19 (or comment them in `settings.gradle`). You need to place the remapped jar in `spigot/spigot18`
Pour les sources et la doc c'était pour être complet, pas besoin de ça en vrai même si ça peut être pratique ^^ effectivement tu peux juste mettre la commande telle que tu l'a écrite.

2022-08-19 14:27 UTC, RedNesto requested changes

2022-08-19 14:27 UTC, RedNesto commented on README.md
> + You need to place the jar in `spigot/spigot18` if you want 1.18 and you have comment others ones. If you want other version, do the same thing for `spigot/spigot17` etc...
Pas besoin de déplacer les jars.

2022-08-19 15:36 UTC, Farmeurimmo commented on README.md
> + You need to place the jar in `spigot/spigot18` if you want 1.18 and you have comment others ones. If you want other version, do the same thing for `spigot/spigot17` etc...
Déplacer les jars ? J'ai pas compris

2022-08-19 15:56 UTC, Elikill58 commented on README.md
> + You need to place the jar in `spigot/spigot18` if you want 1.18 and you have comment others ones. If you want other version, do the same thing for `spigot/spigot17` etc...
Une fois que tu as remapped, avec `mavenLocal()` ça ira chercher dans ton dossier `~/m2` sans avoir besoin de copier le fichier

2022-08-19 16:00 UTC, Farmeurimmo commented on README.md
> + You need to place the jar in `spigot/spigot18` if you want 1.18 and you have comment others ones. If you want other version, do the same thing for `spigot/spigot17` etc...
Ah ok, mais si la personne compile sa sur une machine autre que celle où il a compilé son jar ?

2022-08-19 19:42 UTC, RedNesto commented on README.md
> + You need to place the jar in `spigot/spigot18` if you want 1.18 and you have comment others ones. If you want other version, do the same thing for `spigot/spigot17` etc...
Oui, mais du coup on a quand même besoin des jars remappés. C'est peut être possible de copier/coller les fichiers d'un maven local à un autre, ou le faire via des commandes maven pour installer les jars et POMs en local. Dans tous les cas copier les jars tels quels dans les dossiers de Negativity n'est pas supporté.

2022-08-21 17:03 UTC, Farmeurimmo commented on README.md
> + You need to place the jar in `spigot/spigot18` if you want 1.18 and you have comment others ones. If you want other version, do the same thing for `spigot/spigot17` etc...
Pourtant c'est exactement la même chose que vous demandez pour les spigot <= 1.16.5

2022-08-21 18:20 UTC, RedNesto commented on README.md
> + You need to place the jar in `spigot/spigot18` if you want 1.18 and you have comment others ones. If you want other version, do the same thing for `spigot/spigot17` etc...
Non justement pour les versions plus anciennes de spigot on utilise un système différent ou il faut copier les jars. Pour les versions plus récentes, qui ont leur propre sous-projet, on doit remapper les classes et là on utilise des dépendances propres (publiées par buildtools dans maven local.)

2022-08-22 14:06 UTC, Farmeurimmo commented on README.md
> + You need to place the jar in `spigot/spigot18` if you want 1.18 and you have comment others ones. If you want other version, do the same thing for `spigot/spigot17` etc...
Donc tu veux que je change quoi?

2022-08-22 19:02 UTC, RedNesto approved these changes

2022-08-22 19:02 UTC, merged