Add CPU monitor
Elikill58/Negativity pull request #335
Opened 2022-08-19 17:44 UTC by Elikill58

The objective is to be able to have a CPU monitor, and a base to easily add other monitor in future such as RAM

2022-08-19 20:03 UTC, RedNesto requested changes

2022-08-19 20:03 UTC, RedNesto commented on common/src/com/elikill58/negativity/universal/monitor/cpu/function/CpuMeasure.java
> +		return ChatColor.GREEN + (name.isEmpty() ? "" : name + " ") + ChatColor.YELLOW + data.getAverage() + "ns "
Microsecondes ici aussi du coup ?

2022-08-20 07:15 UTC, Elikill58 commented on common/src/com/elikill58/negativity/api/events/EventManager.java
> +					cpuMeasure.add(method.getMethod(), (System.nanoTime() - beginTime) / 1000);
Il n'y a pas de moyen d'avoir les microsecondes, sans /1000 nous-même (https://stackoverflow.com/a/1712215/10952503)

2022-08-20 09:39 UTC, RedNesto approved these changes

2022-08-21 21:02 UTC, merged