Make Fabric use external NegativityFabric dependency
Elikill58/Negativity pull request #342
Opened 2022-09-24 16:25 UTC by Elikill58

The objective is to support all fabric version easily.

You should download fabric build in [NegativityFabric](https://github.com/Elikill58/NegativityFabric).

2022-09-24 16:29 UTC, RedNesto commented
Je vois pas l'intérêt d'utiliser un repo séparé, ça rend le tout plus chiant à gérer pour les maj de common...

2022-09-24 16:32 UTC, Elikill58 commented
De la même manière que ViaVersion. Ici, il est nécessaire d'avoir des jars séparés du principal, pour ça que j'ai aussi séparé les repos

2022-09-24 16:51 UTC, RedNesto commented
Ouais mais pas besoin pour ça, on fait déjà ça pour sponge7 il me semble. Là c'est bien moins pratique.

Suffit de ne pas inclure le projet dans le shadowJar racine et de distribuer les jars compilés par :fabric19:build par exemple

2022-09-26 10:57 UTC, RedNesto requested changes
Du coup on n'a pas de code commun qu'on peut utiliser, de la même manière qu'avec Spigot ?

2022-09-26 10:57 UTC, RedNesto commented on fabric/fabric19/build.gradle
> +    id 'fabric-loom' version '0.12-SNAPSHOT'
```suggestion
    id 'fabric-loom'
```
La version est déjà précisée dans le projet parent, et si les versions diffèrent ont a une erreur à la configuration.

De même pour la 1.19.2.

2022-09-26 10:57 UTC, RedNesto commented on fabric/fabric19/build.gradle
> +
```suggestion

loom {
    serverOnlyMinecraftJar()
}

```

Autrement j'ai une erreur à cause d'une classe multi-version de LWJGL qui requiert Java 19, et puis on n'a pas besoin des classes client pour un mod serveur uniquement.

De même pour la 1.19.2.

2022-09-26 10:57 UTC, RedNesto commented on fabric/fabric19/build.gradle
> +archivesBaseName = 'NegativityFabric-19'
```suggestion
archivesBaseName = 'NegativityFabric-1.19'
```

Ca fait bizarre sinon.

De même pour la 1.19.2.

2022-09-26 10:57 UTC, RedNesto commented on README.md
> +- **Fabric** Check all versions [here](https://github.com/Elikill58/NegativityFabric)
Je préfère avoir les versions directement ici, comme pour les autres plateformes.

2022-09-26 11:46 UTC, Elikill58 commented
> Du coup on n'a pas de code commun qu'on peut utiliser, de la même manière qu'avec Spigot ?

En fait, je pense qu'au fur et à mesure des versions, le remapping vas changer, les mixins aussi etc

2022-09-27 09:11 UTC, RedNesto commented
Je crois que tu as oublié de configurer shadowjar pour fabric19 et fabric 192 ?
Il faudra aussi régler les conflits avant de merge.

2022-09-27 09:32 UTC, Elikill58 commented
De quoi, non il faut pas inclure tout les fabric dans le même jar, c'est ça le truc

2022-09-27 09:43 UTC, RedNesto commented
> De quoi, non il faut pas inclure tout les fabric dans le même jar, c'est ça le truc

Je parle pas de ça, mais du fait que tes jars ne contiennent pas common et tout le reste nécessaire au bon fonctionnement :c

2022-09-27 11:07 UTC, RedNesto commented
Hmm, chuis pas trop convaincu mais si ça marche pour toi

2022-09-28 09:27 UTC, RedNesto approved these changes

2022-09-28 09:27 UTC, merged